import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";

import StoreContext from "./_context/storeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <React.StrictMode>
        <StoreContext>
          <body className={inter.className}>{children}</body>
        </StoreContext>
      </React.StrictMode>
    </html>
  );
}
